### ISSUE TITLE
Touch screen?

### ISSUE THREAD

**Issue by kubsztal** [MitkoDyakov/Roendi#1]
Hi, does Roendi have a touch recognition capability? It's not clear based on the description on Crowd Supply.

**Comment by MitkoDyakov** [comment]
@kubsztal Hi there :) It does not have touch recognition. But when I design it I left enough space for touch screen or glass cover. There is also a way of routing wires from the inside to the outside and a free I2C bus. It is up to the user to extend the capabilities or not. Hope this help. If there there more questions please ask! Stay healthy stay happy!
