### ISSUE TITLE
Encoder + Display without MCU

### ISSUE THREAD

**Issue by skannan89** [MitkoDyakov/Roendi#3]
Hello! 

I saw this on crowd supply. I am designing my custom mechanical keyboard. I have been looking forward to a encoder + display product. 
Since my keyboard already has a MCU, I would prefer a board with pinouts for display and the encoder. Something like this: [RJS-SDE](https://www.rjselectronics.com/products/navigation-switch-rotary-encoder-push-button-rjs-sde/). Their [block diagram](https://www.rjselectronics.com/wp-content/uploads/RJS-SDE-z.pdf) is exactly what I need but their screen is not fully circular and is ugly.
Could you please offer an option without the MCU?

Thanks!

**Comment by MitkoDyakov** [comment]
Hi skannan89

I am not planning a breakout board for now (no MCU). If you are building just one keyboard for yourself what I can offer you is the following.

Aluminum body, encoder, display, display adaptor board and a ribbon cable. If the style of the aluminum body does not suit your needs there are free CAD model that you can use to make your custom design. 

The hole assembly looks like this :

http://xtech.bg/wp-content/uploads/2021/11/IMG_20211105_104247-scaled.jpg
http://xtech.bg/wp-content/uploads/2021/11/IMG_20211105_104258-scaled.jpg
http://xtech.bg/wp-content/uploads/2021/11/IMG_20211105_104256-scaled.jpg

The encoder's pins spacing is 2.54 so you can put it on proto board and for the ribbon cables (red connector) you can use connector like this :

https://www.tag-connect.com/wp-content/uploads/2020/02/STDC14-mock-1200x800.jpg 

which is also 2.54 suitable for mounting on a proto board.

If you don't want to use proto board, footprints for the encoder and connectors for the ribbon cables are available for free.

Cheers,
Mitko

**Comment by skannan89** [comment]
>  If you are building just one keyboard for yourself what I can offer you is the following.
> Aluminum body, encoder, display, display adaptor board and a ribbon cable. If the style of the aluminum body does not suit your needs there are free CAD model that you can use to make your custom design.

Yes! Thanks a lot, really appreciate your offer. That's without the MCU, right? How do I pay you? You can reach me at my username (gmail.com) and we can talk about payment and shipment. 

Have a wonderful day!
