### ISSUE TITLE
Project is alive? 

### ISSUE THREAD

**Issue by littlbee** [MitkoDyakov/Roendi#6]
Hello
Just wondering if this project is still alive? I signed up for updates months ago on crowdsupply, but never received any update so seems the project never got launched (so far)

**Comment by MitkoDyakov** [comment]
Hello, @littlbee 

yes the project is very much alive. We have been busy with the campaign and working out the difficulties related to chip shortages. 

There are updates related to the code base in github repo. Also if you want you can take a look at these instructables as well:

https://www.instructables.com/Roendi-Installation-Tutorial/
https://www.instructables.com/Programming-RoEnDi-With-Arduino-IDE/

Thank you for the interest and support! We are going to launch the campaign in the upcoming weeks.

Cheers!

**Comment by psyspy1** [comment]
Hello @MitkoDyakov 

When can we expect the project to launch? This month?

**Comment by MitkoDyakov** [comment]
Heyy

The project is alive and almost funded! 

Cheers.
