### ISSUE TITLE
Integrating Roendi

### ISSUE THREAD

**Issue by psyspy1** [MitkoDyakov/Roendi#7]
Howdy! 

I am designing my pcb with ESP32 for a home automation project. I am interested in using Roendi to control some lighting, basically use it as a dimmer. I am almost done with designing my pcb in kicad. How do I integrate Roendi with my pcb? 
Do I solder it onto my pcb? 
Or mount Roendi to the plastic enclosure and run wires from pcb to the pads on Roendi?

**Comment by MitkoDyakov** [comment]
Hello @psyspy1

Mounting Roendi to the enclosure seems like the right way to go. You can find 3D models of the whole device in the references folder of this repo to help you with designing the enclosure. 

If you want to connect the two devices via UART for example you will need to run wire connection for RX, TX and GND. 

Hope this helps. If you have any other questions do not hesitate to ask!

Cheers,
Mitko

**Comment by psyspy1** [comment]
Thanks for the update. I saw your project in some news article last year. Anyhow, when can we expect it to launch? end of march?

**Comment by psyspy1** [comment]
> If you want to connect the two devices via UART for example you will need to run wire connection for RX, TX and GND.

And power too, right? I am planning to power it from my board.

**Comment by MitkoDyakov** [comment]
hey @psyspy1 sorry for the late response. 

Yes you can power it from a Vin pin or from USB, but not both. 

Cheers,
Mitko
